version: '3.9'

services:
  django:
    build: 
      context: ./linkCreateAccount
      dockerfile: Dockerfile
    volumes:
      - django_static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./linkCreateAccount/.env
    command: gunicorn linkCreateAccount.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
    ports:
      - 80:80
volumes:
  postgres_data:
  django_static_volume: